#### Columns
MARKET_ID_COLUMN = 'market_id'
DAY_COLUMN = 'day'
STORE_CATEGORY = 'store_primary_category'
STORE_COLUMN = 'store_id'
DATE_COLUMN = 'created_at'
DELIVERY_COLUMN = 'actual_delivery_time'
ORDER_PLACE_DURATION_COLUMN = 'estimated_order_place_duration'
STORE_CLIENT_DURATION_COLUMN = 'estimated_store_to_consumer_driving_duration'
SUBTOTAL_COLUMN = 'subtotal'
TOTAL_DASHERS_COLUMN = 'total_onshift_dashers'
BUSY_DASHERS_COLUMN = 'total_busy_dashers'
AVAILABLE_DASHERS_COLUMN = 'availabe_dashers_onshift'
TOTAL_ORDERS = 'total_outstanding_orders'
WEEK_COLUMN = 'week'
WEEKDAY_COLUMN = 'weekday'
WEEKEND_COLUMN = 'weekend'
HOUR_COLUMN = 'hour'
TIME_OF_DAY_COLUMN = 'time_of_day'
ESTIMATED_DELIVERY_COLUMN = 'estimated_delivery_time'
DELIVERY_TIME_SECONDS_COLUMN = 'delivery_time'
DELIVERY_TIME_HOURS_COLUMN = 'delivery_time_hours'
ORDER_PROTOCOL_COLUMN = 'order_protocol'
ITEMS_COLUMN = 'items'
TRANSACTIONS_COLUMN = 'transactions'
#### Fill na methods
FILL_NA_WITH_NEW_CATEGORY_METHOD = 'fill with new category'
FILL_NA_WITH_MEDIAN_METHOD = 'fill with median'
FILL_NA_WITH_CLUSTER_MEDIAN_METHOD = 'fill with cluster median'
#### Metrics names
REVENUE_METRIC = 'revenue'
N_TRANSACTIONS_METRIC = 'number of transactions'
N_ITEMS_METRIC = 'number of items'
#### KPIs Names
TOTAL_REVENUE = 'total_revenue'
TOTAL_TRANSACTIONS = 'total_transactions'
TOTAL_ITEMS = 'total_items'
DISTINCT_FOOD_CATEGORIES = 'distinct_food_categories'
TOTAL_NUMBER_OF_STORES = 'total_number_of_stores'
AVG_NUMBER_OF_ITEMS = 'avg_number_of_items'
AVG_REVENUE = 'avg_revenue'
P_25_AVG_DAILY_TRANSACTION = 'p25_avg_daily_transaction'
P_75_AVG_DAILY_TRANSACTION = 'p75_avg_daily_transaction'
P_95_AVG_DAILY_TRANSACTION = 'p95_avg_daily_transaction'
#### Plots Names
TIME_SERIES_PLOT = 'time_series_plot'
WEEKDAY_PLOT = 'weekday_plot'
TIME_OF_DAY_PLOT = 'time_of_day_plot'
STORE_RANK_PLOT = 'store_rank'
CATEGORY_RANK_PLOT = 'category_rank'
PROTOCOL_RANK_PLOT = 'protocol_rank'
KPIS = 'kpis'
